title = "Dyte.io UI Kit Sample X Bartholomew"
# logo = "URL to logo"
base_url = "http://localhost:3000"
about = ""
index_site_pages = ["blog"]

[extra]
copyright = "The Site Authors"
github = "https://github.com/fermyon"
twitter = "https://twitter.com/fermyontech"

date_style = "%B %e, %Y"
